# Site settings
title: "websocket.org - Powered by Kaazing"
email: peter.moskovits@kaazing.com
description: "websocket.org - Powered by Kaazing"
baseurl: ""
url: http://www.websocket.org
highlighter: pygments

production: true
# wordpress : true
asseturl: "/websocket.org"

# Build settings
markdown: redcarpet
highlighter: pygments
# permalink: pretty
#categories: [general]
#relative_permalinks: false

redcarpet:
  extensions: ["fenced_code_blocks"]
  input: "GFM"
